-- Run after schema.sql to manage Nigerian state delivery fees.
create table if not exists public.delivery_zones (
    id bigint generated by default as identity primary key,
    state text not null unique,
    fee numeric(10,2) not null default 0 check (fee >= 0),
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
alter table public.delivery_zones enable row level security;
create or replace function public.is_admin() returns boolean language sql security definer set search_path = public stable as $$
    select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;
drop policy if exists "Public can read active delivery zones" on public.delivery_zones;
drop policy if exists "Admins manage delivery zones" on public.delivery_zones;
create policy "Public can read active delivery zones" on public.delivery_zones for select using (is_active = true);
create policy "Admins manage delivery zones" on public.delivery_zones for all to authenticated using (public.is_admin()) with check (public.is_admin());
insert into public.delivery_zones (state, fee) values
('Abia',0),('Adamawa',0),('Akwa Ibom',0),('Anambra',0),('Bauchi',0),('Bayelsa',0),('Benue',0),('Borno',0),('Cross River',0),('Delta',0),('Ebonyi',0),('Edo',0),('Ekiti',0),('Enugu',0),('Gombe',0),('Imo',0),('Jigawa',0),('Kaduna',0),('Kano',0),('Katsina',0),('Kebbi',0),('Kogi',0),('Kwara',0),('Lagos',0),('Nasarawa',0),('Niger',0),('Ogun',0),('Ondo',0),('Osun',0),('Oyo',0),('Plateau',0),('Rivers',0),('Sokoto',0),('Taraba',0),('Yobe',0),('Zamfara',0),('Federal Capital Territory',0)
on conflict (state) do nothing;
