-- Run after the existing schema and admin migrations.
create table if not exists public.product_variations (
    id bigint generated by default as identity primary key,
    product_id bigint not null references public.products(id) on delete cascade,
    name text not null,
    value text not null,
    sku text,
    price_adjustment numeric(10,2) not null default 0,
    stock integer not null default 0 check (stock >= 0),
    is_active boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists public.reviews (
    id bigint generated by default as identity primary key,
    product_id bigint not null references public.products(id) on delete cascade,
    user_id uuid not null references auth.users(id) on delete cascade,
    rating integer not null check (rating between 1 and 5),
    title text,
    body text not null,
    created_at timestamptz not null default now(),
    unique (product_id, user_id)
);

alter table public.product_variations enable row level security;
alter table public.reviews enable row level security;

drop policy if exists "Public can read active product variations" on public.product_variations;
drop policy if exists "Public can read reviews" on public.reviews;
drop policy if exists "Verified buyers can create reviews" on public.reviews;
drop policy if exists "Users update own reviews" on public.reviews;
drop policy if exists "Users delete own reviews" on public.reviews;
drop policy if exists "Admins manage variations" on public.product_variations;
drop policy if exists "Admins manage reviews" on public.reviews;

create policy "Public can read active product variations" on public.product_variations for select using (is_active = true);
create policy "Public can read reviews" on public.reviews for select using (true);
create policy "Verified buyers can create reviews" on public.reviews for insert to authenticated with check (
    auth.uid() = user_id and exists (
        select 1 from public.order_items oi
        join public.orders o on o.id = oi.order_id
        where oi.product_id = reviews.product_id and o.user_id = auth.uid() and o.status = 'delivered'
    )
);
create policy "Users update own reviews" on public.reviews for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users delete own reviews" on public.reviews for delete to authenticated using (auth.uid() = user_id);
create policy "Admins manage variations" on public.product_variations for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "Admins manage reviews" on public.reviews for all to authenticated using (public.is_admin()) with check (public.is_admin());

create index if not exists product_variations_product_id_idx on public.product_variations(product_id);
create index if not exists reviews_product_id_idx on public.reviews(product_id);
