create extension if not exists "pgcrypto";

create table public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    full_name text not null,
    avatar_url text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.categories (
    id bigint generated by default as identity primary key,
    name text not null unique,
    slug text not null unique,
    created_at timestamptz not null default now()
);

create table public.products (
    id bigint generated by default as identity primary key,
    category_id bigint references public.categories(id) on delete set null,
    name text not null,
    slug text not null unique,
    description text,
    price numeric(10,2) not null check (price >= 0),
    compare_at_price numeric(10,2) check (compare_at_price is null or compare_at_price >= price),
    stock integer not null default 0 check (stock >= 0),
    is_featured boolean not null default false,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.product_images (
    id bigint generated by default as identity primary key,
    product_id bigint not null references public.products(id) on delete cascade,
    image_url text not null,
    alt_text text,
    sort_order integer not null default 0,
    created_at timestamptz not null default now()
);

create table public.product_variations (
    id bigint generated by default as identity primary key,
    product_id bigint not null references public.products(id) on delete cascade,
    name text not null,
    value text not null,
    sku text,
    price_adjustment numeric(10,2) not null default 0,
    stock integer not null default 0 check (stock >= 0),
    is_active boolean not null default true,
    created_at timestamptz not null default now()
);

create table public.reviews (
    id bigint generated by default as identity primary key,
    product_id bigint not null references public.products(id) on delete cascade,
    user_id uuid not null references auth.users(id) on delete cascade,
    rating integer not null check (rating between 1 and 5),
    title text,
    body text not null,
    created_at timestamptz not null default now(),
    unique (product_id, user_id)
);

create table public.orders (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete restrict,
    status text not null default 'pending' check (status in ('pending', 'confirmed', 'declined', 'on the way', 'delivered')),
    total numeric(10,2) not null default 0 check (total >= 0),
    payment_reference text,
    payment_status text not null default 'unpaid' check (payment_status in ('pending', 'unpaid', 'paid', 'failed', 'refunded')),
    payment_method text not null default 'paystack',
    payment_proof_url text,
    payment_method text not null default 'paystack',
    payment_proof_url text,
    shipping_address jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.order_items (
    id bigint generated by default as identity primary key,
    order_id uuid not null references public.orders(id) on delete cascade,
    product_id bigint not null references public.products(id) on delete restrict,
    quantity integer not null check (quantity > 0),
    unit_price numeric(10,2) not null check (unit_price >= 0)
);

create table public.site_settings (
    id boolean primary key default true check (id),
    store_name text not null default 'DTT',
    seo_title text not null default 'DTT | Thoughtful finds for every day',
    seo_description text not null default 'Discover considered products across fashion, beauty, food, gifts and more.',
    logo_url text,
    logo_width integer not null default 96 check (logo_width between 24 and 320),
    favicon_url text,
    hero_eyebrow text not null default 'WELCOME TO DTT',
    hero_title text not null default 'Everything You Love, All In One Place.',
    hero_description text not null default 'Cakes, fashion, beauty, gifts, accessories and more.',
    hero_button_text text not null default 'SHOP NOW',
    hero_button_link text not null default 'products.html',
    hero_image_url text,
    contact_email text not null default 'hello@dtt.store',
    contact_phone text not null default '+234 000 000 0000',
    contact_address text not null default 'Add your store address',
    contact_hours text not null default 'Monday - Saturday, 9:00 AM - 6:00 PM',
    contact_instagram text,
    paystack_public_key text,
    payment_currency text not null default 'NGN',
    payments_enabled boolean not null default false,
    manual_payment_enabled boolean not null default false,
    bank_name text,
    bank_account_name text,
    bank_account_number text,
    bank_instructions text,
    manual_payment_enabled boolean not null default false,
    bank_name text,
    bank_account_name text,
    bank_account_number text,
    bank_instructions text,
    updated_at timestamptz not null default now()
);

create table public.delivery_zones (
    id bigint generated by default as identity primary key,
    state text not null unique,
    fee numeric(10,2) not null default 0 check (fee >= 0),
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$
begin
    insert into public.profiles (id, full_name) values (new.id, coalesce(new.raw_user_meta_data->>'full_name', 'DTT shopper'));
    return new;
end;
$$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;
alter table public.product_variations enable row level security;
alter table public.reviews enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

create policy "Public can read categories" on public.categories for select using (true);
create policy "Public can read active products" on public.products for select using (is_active = true);
create policy "Public can read product images" on public.product_images for select using (exists (select 1 from public.products p where p.id = product_id and p.is_active));
create policy "Users read own profile" on public.profiles for select using (auth.uid() = id);
create policy "Users update own profile" on public.profiles for update using (auth.uid() = id);
create policy "Users read own orders" on public.orders for select using (auth.uid() = user_id);
create policy "Users create own orders" on public.orders for insert with check (auth.uid() = user_id);
create policy "Users update own orders" on public.orders for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users read own order items" on public.order_items for select using (exists (select 1 from public.orders o where o.id = order_id and o.user_id = auth.uid()));
create policy "Users create own order items" on public.order_items for insert with check (exists (select 1 from public.orders o where o.id = order_id and o.user_id = auth.uid()));
create policy "Public can read active product variations" on public.product_variations for select using (is_active = true);
create policy "Public can read reviews" on public.reviews for select using (true);
create policy "Verified buyers can create reviews" on public.reviews for insert to authenticated with check (auth.uid() = user_id and exists (select 1 from public.order_items oi join public.orders o on o.id = oi.order_id where oi.product_id = reviews.product_id and o.user_id = auth.uid() and o.status = 'delivered'));
create policy "Users update own reviews" on public.reviews for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users delete own reviews" on public.reviews for delete to authenticated using (auth.uid() = user_id);
create index products_category_id_idx on public.products(category_id);
create index product_images_product_id_idx on public.product_images(product_id);
create index orders_user_id_idx on public.orders(user_id);

insert into storage.buckets (id, name, public) values ('product-images', 'product-images', true)
on conflict (id) do nothing;
create policy "Anyone can view product images" on storage.objects for select using (bucket_id = 'product-images');
create policy "Authenticated users can upload product images" on storage.objects for insert to authenticated with check (bucket_id = 'product-images');

insert into public.categories (name, slug) values
    ('Food', 'food'), ('Beauty', 'beauty'), ('Fashion', 'fashion'), ('Jewelry', 'jewelry'),
    ('Perfumes', 'perfumes'), ('Gifts', 'gifts'), ('Decor', 'decor'), ('Gadgets', 'gadgets')
on conflict (slug) do nothing;